spring:
  application:
    name: Quest Project
  main:
    banner-mode: 'off'
  datasource:
    url: jdbc:mysql://localhost:3306/quest_and_answer?serverTimezone=Europe/Minsk&useSSL=false
    username: user
    password: 123456
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        enable_lazy_loading_no_trans: true
    hibernate:
      ddl-auto: validate
